name: First Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print the date
        run: date

  job2:
    runs-on: windows-latest
    steps:
      - name: Print the date
        run: echo %date%

  job3: 
    runs-on: macos-latest
    steps:
      - name: Print the date
        run: date

  job4:
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: Print the date
        run: date

  
    
